In [7]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
print(arr[:])       # slicing with step 1
print(arr[::2])       # slicing with step 2
print(arr[1:5])       # slicing from index 1 to 4


[10 20 30 40 50]
[10 30 50]


reverse array

In [9]:
print(arr[::-1])       # Accessing the first element

[50 40 30 20 10]
