np.insert(array, index, value, axis = None)
array - original array
index - 
value -
axis -
axis = 0 - row wise
axis = 1 - column wise
axis = None -flatten - single line

In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])


In [17]:
newarr = np.insert(arr, 2, 7, axis = None)
print(newarr)  

[1 2 7 3 4 5 6]


insert in 2d array

In [18]:
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6]])
newarr2d = np.insert(arr_2d, 3, 7, axis = 1)
print(newarr2d)

[[1 2 3 7]
 [4 5 6 7]]


insert a new row at index 1

In [19]:
newraw = np.insert(arr_2d, 1, [7,8,9], axis = 0)
print(newraw)

[[1 2 3]
 [7 8 9]
 [4 5 6]]
