Types of array

1 dimensional array

In [1]:
import numpy as np
ar_1d = np.array([10,20,30,40,50])
ar_1d

array([10, 20, 30, 40, 50])

Two dimensional array

In [2]:
ar_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(ar_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Multy Dimensional array or matrix array

In [3]:
matrix = np.array([[2,4,6],
                   [8,10,12]])
print(matrix)

[[ 2  4  6]
 [ 8 10 12]]
