#crating arrays from python list
#nnp.array([ele1, ele2, ele3])

In [5]:
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

#with default values we can change values in future
#np.zeros(shape) (3) <----for 1D,   for 2D -->(3,3) 

In [8]:
zeros_array = np.zeros(3)
print(zeros_array)

[0. 0. 0.]


#ones(shape  )   making 1 ad default values

In [11]:
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


full(shape, value)


In [12]:
filled_array = np.full((2,2),7)
filled_array

array([[7, 7],
       [7, 7]])

#creating sequences of numbers in numpy

#arrange(start,stop,step)

In [15]:
arr_arange = np.arange(1,10,2)
print(arr_arange)
type(arr_arange)

[1 3 5 7 9]


numpy.ndarray

#creating identiy matrices , 1 in diagonal and zero elsewhere
#eye(size)

In [ ]:
identity_matrix = np.eye(3)     
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])