In [3]:
import numpy as np
arr = np.array([10, 20, 30, 40])


In [4]:
print(arr + 5)
print(arr - 5)
print(arr * 5)
print(arr / 5)
print(arr % 5)
print(arr ** 2)

[15 25 35 45]
[ 5 15 25 35]
[ 50 100 150 200]
[2. 4. 6. 8.]
[0 0 0 0]
[ 100  400  900 1600]
