<a href="https://colab.research.google.com/github/pravinMchavan/ML-Portfolio/blob/main/ML-Portfolio%20/numpy_learning/1_types_of_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Types of array

1 dimensional array

In [ ]:
import numpy as np
ar_1d = np.array([10,20,30,40,50])
ar_1d

array([10, 20, 30, 40, 50])

Two dimensional array

In [ ]:
ar_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(ar_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Multy Dimensional array

In [ ]:
matrix = np.array([[2,4,6],
                   [8,10,12]])
print(matrix)

[[ 2  4  6]
 [ 8 10 12]]
